// app/layout.tsx
import { UserProvider } from './context/UserContext';  // Adjust the path if needed
import Navbar from "@/component/Navbar/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider> {/* Wrap the entire app with UserProvider */}
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
