export const UserTasks = [
    {
      _id: "661ff12d3b1dcae3d2d1e9a7",
      title: "Complete Assignment",
      description: "Work on Marrow Fullstack Assessment",
      tags: ["assignment", "urgent"],
      priority: "High",
      assignedTo: "anirudh",
      createdAt: "2024-04-26T10:00:00.000Z",
    },
    {
      _id: "771ff12d3b1dcae3d2d1e9b8",
      title: "Finish Documentation",
      description: "Complete API docs for the app",
      tags: ["documentation", "work"],
      priority: "Medium",
      assignedTo: "komal",
      createdAt: "2024-04-25T08:30:00.000Z",
    },
    {
      _id: "881ff12d3b1dcae3d2d1e9c9",
      title: "Bug Fix in UI",
      description: "Fix the layout issue in the homepage header",
      tags: ["bug", "urgent"],
      priority: "High",
      assignedTo: "komal",
      createdAt: "2024-04-26T10:45:00.000Z",
    },
    {
      _id: "991ff12d3b1dcae3d2d1e9d0",
      title: "Product Research",
      description: "Conduct research on competitors' products",
      tags: ["research", "work"],
      priority: "Medium",
      assignedTo: "anirudh",
      createdAt: "2024-04-24T09:00:00.000Z",
    },
    {
      _id: "102ff12d3b1dcae3d2d1e9d1",
      title: "Write Unit Tests",
      description: "Write unit tests for the new features in the app",
      tags: ["development", "testing"],
      priority: "Low",
      assignedTo: "suraj",
      createdAt: "2024-04-23T12:30:00.000Z",
    },
    {
      _id: "112ff12d3b1dcae3d2d1e9d2",
      title: "Design Mockups",
      description: "Create mockups for the new dashboard",
      tags: ["design", "work"],
      priority: "Medium",
      assignedTo: "komal",
      createdAt: "2024-04-22T14:00:00.000Z",
    },
    {
      _id: "122ff12d3b1dcae3d2d1e9d3",
      title: "Database Optimization",
      description: "Optimize database queries for better performance",
      tags: ["database", "optimization"],
      priority: "High",
      assignedTo: "anirudh",
      createdAt: "2024-04-21T11:00:00.000Z",
    },
    {
      _id: "132ff12d3b1dcae3d2d1e9d4",
      title: "Team Meeting",
      description: "Discuss project progress and next steps",
      tags: ["meeting", "team"],
      priority: "Low",
      assignedTo: "suraj",
      createdAt: "2024-04-20T09:30:00.000Z",
    },
    {
      _id: "142ff12d3b1dcae3d2d1e9d5",
      title: "Code Review",
      description: "Review pull requests for the latest features",
      tags: ["review", "development"],
      priority: "Medium",
      assignedTo: "komal",
      createdAt: "2024-04-19T16:00:00.000Z",
    },
    {
      _id: "152ff12d3b1dcae3d2d1e9d6",
      title: "Write Blog Post",
      description: "Write a blog post about the app's new features",
      tags: ["content", "marketing"],
      priority: "Low",
      assignedTo: "anirudh",
      createdAt: "2024-04-18T10:00:00.000Z",
    },
    {
      _id: "162ff12d3b1dcae3d2d1e9d7",
      title: "Fix Backend Bug",
      description: "Resolve the issue with user authentication",
      tags: ["bug", "backend"],
      priority: "High",
      assignedTo: "suraj",
      createdAt: "2024-04-17T13:00:00.000Z",
    },
    {
      _id: "172ff12d3b1dcae3d2d1e9d8",
      title: "Prepare Presentation",
      description: "Prepare slides for the client meeting",
      tags: ["presentation", "work"],
      priority: "Medium",
      assignedTo: "komal",
      createdAt: "2024-04-16T15:00:00.000Z",
    },
    {
      _id: "182ff12d3b1dcae3d2d1e9d9",
      title: "Update Dependencies",
      description: "Update project dependencies to the latest versions",
      tags: ["maintenance", "development"],
      priority: "Low",
      assignedTo: "anirudh",
      createdAt: "2024-04-15T12:00:00.000Z",
    },
    {
      _id: "192ff12d3b1dcae3d2d1e9e0",
      title: "User Feedback Analysis",
      description: "Analyze feedback from beta testers",
      tags: ["feedback", "analysis"],
      priority: "Medium",
      assignedTo: "suraj",
      createdAt: "2024-04-14T11:00:00.000Z",
    },
    {
      _id: "202ff12d3b1dcae3d2d1e9e1",
      title: "Deploy New Version",
      description: "Deploy the latest version of the app to production",
      tags: ["deployment", "urgent"],
      priority: "High",
      assignedTo: "komal",
      createdAt: "2024-04-13T14:00:00.000Z",
    },
    {
        _id: "661ff12d3b1dcae3dd2d1e9a7",
        title: "Complete Assignment",
        description: "Work on Marrow Fullstack Assessment",
        tags: ["assignment", "urgent"],
        priority: "High",
        assignedTo: "anirudh",
        createdAt: "2024-04-26T10:00:00.000Z",
      },
      {
        _id: "771ff12d3b1dcae3gd2d1e9b8",
        title: "Finish Documentation",
        description: "Complete API docs for the app",
        tags: ["documentation", "work"],
        priority: "Medium",
        assignedTo: "komal",
        createdAt: "2024-04-25T08:30:00.000Z",
      },
      {
        _id: "881ff12d3b1pd1cae3d2d1e9c9",
        title: "Bug Fix in UI",
        description: "Fix the layout issue in the homepage header",
        tags: ["bug", "urgent"],
        priority: "High",
        assignedTo: "komal",
        createdAt: "2024-04-26T10:45:00.000Z",
      },
      {
        _id: "991ff12d3b1dhcae03d2d1e9d0",
        title: "Product Research",
        description: "Conduct research on competitors' products",
        tags: ["research", "work"],
        priority: "Medium",
        assignedTo: "anirudh",
        createdAt: "2024-04-24T09:00:00.000Z",
      },
      {
        _id: "102ff12d3b1dcae33d12d1e9d1",
        title: "Write Unit Tests",
        description: "Write unit tests for the new features in the app",
        tags: ["development", "testing"],
        priority: "Low",
        assignedTo: "suraj",
        createdAt: "2024-04-23T12:30:00.000Z",
      },
      {
        _id: "112ff12d3b1dcae3d2rd1e9d2",
        title: "Design Mockups",
        description: "Create mockups for the new dashboard",
        tags: ["design", "work"],
        priority: "Medium",
        assignedTo: "komal",
        createdAt: "2024-04-22T14:00:00.000Z",
      },
      {
        _id: "122ff12d3b1dcaeh3d2d1e9d3",
        title: "Database Optimization",
        description: "Optimize database queries for better performance",
        tags: ["database", "optimization"],
        priority: "High",
        assignedTo: "anirudh",
        createdAt: "2024-04-21T11:00:00.000Z",
      },
      {
        _id: "132ff12d3b1dcaex3d2d1e9d4",
        title: "Team Meeting",
        description: "Discuss project progress and next steps",
        tags: ["meeting", "team"],
        priority: "Low",
        assignedTo: "suraj",
        createdAt: "2024-04-20T09:30:00.000Z",
      },
      {
        _id: "142ff12d3b1dcae3da2d1e9d5",
        title: "Code Review",
        description: "Review pull requests for the latest features",
        tags: ["review", "development"],
        priority: "Medium",
        assignedTo: "komal",
        createdAt: "2024-04-19T16:00:00.000Z",
      },
      {
        _id: "152ff12d3b1dcae3d2d1he9d6",
        title: "Write Blog Post",
        description: "Write a blog post about the app's new features",
        tags: ["content", "marketing"],
        priority: "Low",
        assignedTo: "anirudh",
        createdAt: "2024-04-18T10:00:00.000Z",
      },
      {
        _id: "162ff12d3bf1dcae3d2d1e9d7",
        title: "Fix Backend Bug",
        description: "Resolve the issue with user authentication",
        tags: ["bug", "backend"],
        priority: "High",
        assignedTo: "suraj",
        createdAt: "2024-04-17T13:00:00.000Z",
      },
      {
        _id: "172ff12d3b1dcaea3d2d1e9d8",
        title: "Prepare Presentation",
        description: "Prepare slides for the client meeting",
        tags: ["presentation", "work"],
        priority: "Medium",
        assignedTo: "komal",
        createdAt: "2024-04-16T15:00:00.000Z",
      },
      {
        _id: "182ff12d3b1dcae3dg2d1e9d9",
        title: "Update Dependencies",
        description: "Update project dependencies to the latest versions",
        tags: ["maintenance", "development"],
        priority: "Low",
        assignedTo: "anirudh",
        createdAt: "2024-04-15T12:00:00.000Z",
      },
      {
        _id: "192ff12d3b1dcaae3d2d1e9e0",
        title: "User Feedback Analysis",
        description: "Analyze feedback from beta testers",
        tags: ["feedback", "analysis"],
        priority: "Medium",
        assignedTo: "suraj",
        createdAt: "2024-04-14T11:00:00.000Z",
      },
      {
        _id: "202ff12d3b1dcaed3d2d1e9e1",
        title: "Deploy New Version",
        description: "Deploy the latest version of the app to production",
        tags: ["deployment", "urgent"],
        priority: "High",
        assignedTo: "komal",
        createdAt: "2024-04-13T14:00:00.000Z",
      },
  ];